// @/api/mockApi/sidebar.ts
import { type SidebarModuleItem, type SidebarSubModuleItem } from '@/types/Sidebar.types';

export const sidebarData = {
  modules: [
    {
      id: 'dashboard',
      label: 'Dashboard',
      icon: 'dashboard',
      iconSize: 20,
      requiredRoles: [],
      order: 10,
      isActive: true,
    },
    {
      id: 'admin',
      label: 'Administration',
      icon: 'shield',
      iconSize: 20,
      requiredRoles: ['admin'],
      order: 20,
      isActive: true,
    },
    {
      id: 'academics',
      label: 'Academics',
      icon: 'book',
      iconSize: 20,
      requiredRoles: ['admin', 'teacher', 'student'],
      order: 30,
      isActive: true,
    },
  ] as SidebarModuleItem[],

  subModules: [
    {
      id: 'admin-dashboard',
      moduleId: 'dashboard',
      label: 'Admin Dashboard',
      path: '/dashboard/admin',
      icon: 'dashboard',
      iconSize: 16,
      requiredRoles: ['admin'],
      order: 10,
      isActive: true,
    },
    {
      id: 'user-management',
      moduleId: 'admin',
      label: 'User Management',
      path: '/admin/users',
      icon: 'users',
      iconSize: 16,
      requiredRoles: ['admin'],
      order: 10,
      isActive: true,
    },
    {
      id: 'teacher-dashboard',
      moduleId: 'dashboard',
      label: 'Teacher Dashboard',
      path: '/dashboard/teacher',
      icon: 'dashboard',
      iconSize: 16,
      requiredRoles: ['teacher'],
      order: 20,
      isActive: true,
    },
    {
      id: 'courses',
      moduleId: 'academics',
      label: 'Courses',
      path: '/academics/courses',
      icon: 'graduationCap',
      iconSize: 16,
      requiredRoles: ['admin', 'teacher', 'student'],
      order: 10,
      isActive: true,
    },
    {
      id: 'course-list',
      moduleId: 'academics',
      label: 'Course List',
      path: '/academics/courses/list',
      icon: 'fileText',
      iconSize: 14,
      requiredRoles: ['admin', 'teacher', 'student'],
      order: 10,
      isActive: true,
      parentId: 'courses',
    },
  ] as SidebarSubModuleItem[],
};
