import {
  LayoutDashboard,
  Book,
  Library,
  Heart,
  Settings,
  Users,
  FileText,
  Calendar,
  Building,
  BarChart,
  GraduationCap,
  BookOpen,
  Mail,
  MessageSquare,
  Bell,
  Search,
  ShoppingBag,
  Home,
  User,
  Shield,
  Briefcase,
  Layers,
  PieChart,
  CreditCard,
  HelpCircle,
  FileQuestion,
  Clipboard,
  Newspaper,
  Award,
  Bookmark,
  Truck,
  Map,
  Headphones,
  Video,
  Image,
  Folder,
  Database,
  Server,
  Code,
  Terminal,
  Cloud,
  Lock,
  Key,
  UserLock,
  GlobeLock,
  Boxes,
  Waypoints,
} from 'lucide-react';
export const iconMap = {
  dashboard: LayoutDashboard,
  userLock: UserLock,
  globeLock: GlobeLock,
  book: Book,
  library: Library,
  heart: Heart,
  settings: Settings,
  users: Users,
  fileText: FileText,
  calendar: Calendar,
  building: Building,
  barChart: BarChart,
  graduationCap: GraduationCap,
  bookOpen: BookOpen,
  mail: Mail,
  messageSquare: MessageSquare,
  bell: Bell,
  search: Search,
  shoppingBag: ShoppingBag,
  home: Home,
  user: User,
  shield: Shield,
  briefcase: Briefcase,
  layers: Layers,
  pieChart: PieChart,
  creditCard: CreditCard,
  helpCircle: HelpCircle,
  fileQuestion: FileQuestion,
  clipboard: Clipboard,
  newspaper: Newspaper,
  award: Award,
  bookmark: Bookmark,
  truck: Truck,
  map: Map,
  headphones: Headphones,
  video: Video,
  image: Image,
  folder: Folder,
  database: Database,
  server: Server,
  code: Code,
  terminal: Terminal,
  cloud: Cloud,
  lock: Lock,
  key: Key,
  boxes: Boxes,
  path: Waypoints,
};
